[tool.poetry]
name = "autopickup"
version = "0.0.1"
description = "An homework autocheck tool"
authors = ["Alkaidcc <932214806@qq.com>"]
license = "MIT"
readme = "README.md"


[tool.config]
XlsxPath = 'D:\Develop\Py\test.xlsx'
ScanPath = ['path1','path2']


